// <auto-generated />
using System;
using DroneDelivery.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DroneDelivery.Api.Migrations
{
    [DbContext(typeof(DroneDeliveryDbContext))]
    [Migration("20260726135554_AddDroneCrudAndSettings")]
    partial class AddDroneCrudAndSettings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("DroneDelivery.Api.Models.Delivery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AllocatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CompletedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DeliveringStartedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DeliveryDurationSeconds")
                        .HasColumnType("int");

                    b.Property<decimal>("DestinationX")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("DestinationY")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("DroneId")
                        .HasColumnType("int");

                    b.Property<decimal>("EndX")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("EndY")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("EstimatedBatteryConsumptionPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("EstimatedDistanceKm")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("EstimatedDurationMinutes")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("FlyingStartedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("LoadingDurationSeconds")
                        .HasColumnType("int");

                    b.Property<DateTime>("LoadingStartedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("OutboundFlightDurationSeconds")
                        .HasColumnType("int");

                    b.Property<int>("ReturnFlightDurationSeconds")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReturningStartedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("StartX")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("StartY")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("DroneId");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("Deliveries", (string)null);
                });

            modelBuilder.Entity("DroneDelivery.Api.Models.DeliveryOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<decimal>("DestinationX")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("DestinationY")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("PackageWeightKg")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("QueueStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("QueuedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("QueueStatus");

                    b.HasIndex("QueuedAtUtc");

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("DroneDelivery.Api.Models.Drone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AverageSpeedKmPerHour")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("BatteryAtChargingStartPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("BatteryConsumptionPercentagePerKm")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("BatteryLevelPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("BatterySafetyMarginPercentagePoints")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime?>("ChargingCompletedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("ChargingRatePercentagePointsPerSecond")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime?>("ChargingStartedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("CurrentX")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("CurrentY")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("MaxPackageWeightKg")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("MaxRangeKm")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("IsActive");

                    b.HasIndex("Status");

                    b.ToTable("Drones", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AverageSpeedKmPerHour = 60m,
                            BatteryConsumptionPercentagePerKm = 1.5m,
                            BatteryLevelPercent = 100m,
                            BatterySafetyMarginPercentagePoints = 5m,
                            ChargingRatePercentagePointsPerSecond = 2m,
                            Code = "DRN-001",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentX = 0m,
                            CurrentY = 0m,
                            IsActive = true,
                            MaxPackageWeightKg = 2.5m,
                            MaxRangeKm = 20m,
                            Name = "Drone leve",
                            Status = "Idle",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            AverageSpeedKmPerHour = 60m,
                            BatteryConsumptionPercentagePerKm = 1.5m,
                            BatteryLevelPercent = 85m,
                            BatterySafetyMarginPercentagePoints = 5m,
                            ChargingRatePercentagePointsPerSecond = 2m,
                            Code = "DRN-002",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentX = 2m,
                            CurrentY = 1m,
                            IsActive = true,
                            MaxPackageWeightKg = 5m,
                            MaxRangeKm = 35m,
                            Name = "Drone medio",
                            Status = "Idle",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            AverageSpeedKmPerHour = 60m,
                            BatteryConsumptionPercentagePerKm = 1.5m,
                            BatteryLevelPercent = 70m,
                            BatterySafetyMarginPercentagePoints = 5m,
                            ChargingRatePercentagePointsPerSecond = 2m,
                            Code = "DRN-003",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentX = -3m,
                            CurrentY = 4m,
                            IsActive = true,
                            MaxPackageWeightKg = 10m,
                            MaxRangeKm = 60m,
                            Name = "Drone pesado",
                            Status = "Idle",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("DroneDelivery.Api.Models.DroneSettings", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<decimal>("BatterySafetyMarginPercentagePoints")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("DroneSettings", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BatterySafetyMarginPercentagePoints = 5m,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("DroneDelivery.Api.Models.NoFlyZone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("NoFlyZones");
                });

            modelBuilder.Entity("DroneDelivery.Api.Models.NoFlyZonePoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("NoFlyZoneId")
                        .HasColumnType("int");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.Property<decimal>("X")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("Y")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("NoFlyZoneId", "Sequence")
                        .IsUnique();

                    b.ToTable("NoFlyZonePoints");
                });

            modelBuilder.Entity("DroneDelivery.Api.Models.Trip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BatteryAtDeparturePercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("BatterySafetyMarginPercentagePoints")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("CompletedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DeliveringStartedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DeliveryDurationSeconds")
                        .HasColumnType("int");

                    b.Property<int>("DroneId")
                        .HasColumnType("int");

                    b.Property<decimal>("EstimatedBatteryConsumptionPercentagePoints")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("EstimatedDistanceKm")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("ExpectedBatteryAtReturnPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("FlyingStartedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("LoadingDurationSeconds")
                        .HasColumnType("int");

                    b.Property<DateTime>("LoadingStartedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("MinimumRequiredBatteryPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("OutboundFlightDurationSeconds")
                        .HasColumnType("int");

                    b.Property<DateTime>("PlannedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ReturnFlightDurationSeconds")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReturningStartedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<decimal>("TotalWeightKg")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("DroneId");

                    b.HasIndex("Status");

                    b.ToTable("Trips", (string)null);
                });

            modelBuilder.Entity("DroneDelivery.Api.Models.TripOrder", b =>
                {
                    b.Property<int>("TripId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DeliveryCompletedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DeliverySequence")
                        .HasColumnType("int");

                    b.Property<DateTime>("DeliveryStartedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("EstimatedArrivalAtUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("TripId", "OrderId");

                    b.HasIndex("OrderId");

                    b.HasIndex("TripId", "DeliverySequence")
                        .IsUnique();

                    b.ToTable("TripOrders", (string)null);
                });

            modelBuilder.Entity("DroneDelivery.Api.Models.Delivery", b =>
                {
                    b.HasOne("DroneDelivery.Api.Models.Drone", "Drone")
                        .WithMany("Deliveries")
                        .HasForeignKey("DroneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DroneDelivery.Api.Models.DeliveryOrder", "Order")
                        .WithOne("Delivery")
                        .HasForeignKey("DroneDelivery.Api.Models.Delivery", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Drone");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("DroneDelivery.Api.Models.NoFlyZonePoint", b =>
                {
                    b.HasOne("DroneDelivery.Api.Models.NoFlyZone", "NoFlyZone")
                        .WithMany("Points")
                        .HasForeignKey("NoFlyZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NoFlyZone");
                });

            modelBuilder.Entity("DroneDelivery.Api.Models.Trip", b =>
                {
                    b.HasOne("DroneDelivery.Api.Models.Drone", "Drone")
                        .WithMany("Trips")
                        .HasForeignKey("DroneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Drone");
                });

            modelBuilder.Entity("DroneDelivery.Api.Models.TripOrder", b =>
                {
                    b.HasOne("DroneDelivery.Api.Models.DeliveryOrder", "Order")
                        .WithMany("TripOrders")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DroneDelivery.Api.Models.Trip", "Trip")
                        .WithMany("TripOrders")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("DroneDelivery.Api.Models.DeliveryOrder", b =>
                {
                    b.Navigation("Delivery");

                    b.Navigation("TripOrders");
                });

            modelBuilder.Entity("DroneDelivery.Api.Models.Drone", b =>
                {
                    b.Navigation("Deliveries");

                    b.Navigation("Trips");
                });

            modelBuilder.Entity("DroneDelivery.Api.Models.NoFlyZone", b =>
                {
                    b.Navigation("Points");
                });

            modelBuilder.Entity("DroneDelivery.Api.Models.Trip", b =>
                {
                    b.Navigation("TripOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
